apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /frontend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /issues(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: issue-service
                port:
                  number: 8080

          - path: /history(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: history-service
                port:
                  number: 8081

          - path: /kibana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kibana
                port:
                  number: 5601
